### ISSUE TITLE
Escrever posição dos estímulos

### ISSUE THREAD

**Issue by AtilaCedro** [cpicanco/stimulus_control#42]
- Na opção de escrever as disposições dos estímulos na tela, quando tento colocar 1 linha e 3 colunas o programa acusa o erro de acess violation (o erro que se der ok corrompe os dados, se der cancel fecha o programa).

**Comment by cpicanco** [comment]
Olá Átila, eu não consegui replicar esse erro. Talvez seja um erro entre plataformas  32 (a sua máquina) e 64 bits (a minha).

**Comment by AtilaCedro** [comment]
Nesta versão mais atual (11/05), não está mais dando este erro.
