### ISSUE TITLE
O último modelo auditivo programado se mantém nas demais tentativas

### ISSUE THREAD

**Issue by AtilaCedro** [cpicanco/stimulus_control#43]
- Está apresentado o mesmo estímulo modelo auditivo em todas as tentativas. No caso, apresentada o último modelo auditivo carregado. Por exemplo, eu programei oito tentativas. A oitava foi com Sol sustenido menor (G#m). Quando fui rodar, o Stimulus Control apresentou o G#m em todas as oito tentativas. Ao conferir o arquivo TXT que é gerado, o nome da tentativa é aquela do arquivo que se quis carregar, mas o Sstm é o arquivo da ultima tentativa programada. Abaixo um exemplo do que estou falando:
[Blc 1 - T7]
Kind=MTS
Name=Acordes_projeto_borges_F#->maior
Cursor=0
SStm=Acordes_projeto_borges_G#m.wav 1 12632256 (onde esta "G#m.wav" deveria ser F#.wav, indicando o estímulo modelo S+ no caso desta tentativa é o F#).
Se eu entrar no arquivo TXT e mudar os "SStm" um por um manualmente funciona.

**Comment by cpicanco** [comment]
Este erro já deve ter sido corrigido. Atualize e teste, por favor!

**Comment by AtilaCedro** [comment]
Já está sim. 
Eu postei para atualizar apenas.

**Comment by cpicanco** [comment]
Grato!
