### ISSUE TITLE
O estímulo comparação considerado correto em todas as tentativas é da última tentativa programada

### ISSUE THREAD

**Issue by AtilaCedro** [cpicanco/stimulus_control#44]
- Acompanhando o bug anterior, a resposta considerada correta em todas as tentativas é aquela que foi programada na última tentativa. Então, se na última tentativa programada a resposta certa foi considerada escolher a palavra menor, esta fica para todas as tentativas programadas até então. Um exemplo disto abaixo, nas linhas de TXT:
[Blc 1 - T6]
Kind=MTS
Name=Acordes_projeto_borges_C#->maior (exemplo do erro anterior)
Cursor=0
SStm=Acordes_projeto_borges_G#m.wav 1 12632256 (exemplo do erro anterior)
SSch=CRF
NumComp=2
C1IET=Rpositivo.png 0 0 1000
C1Res=HIT
C1Stm=menor.png 0 12632256 (o certo aqui seria maior.png)
C1Sch=CRF
C1Nxt=
C1TO=
C2IET=X.png 0 0 1000
C2Res=MISS
C2Stm=maior.png 0 12632256 B (o certo aqui seria menor.png).

Se a alteração for feita direto no arquivo TXT, colocando maior.png e menor.png nos lugares certos, funciona.

**Comment by AtilaCedro** [comment]
Foi corrigido sim. Postei o bug aqui apenas para deixar o fórum atualizado.

**Comment by cpicanco** [comment]
Obrigado!
