### ISSUE TITLE
Apresentação variável das consequências

### ISSUE THREAD

**Issue by AtilaCedro** [cpicanco/stimulus_control#45]
Quando a consequência é um arquivo de som (.wav) ela é apresentada. Quando a consequência é arquivo de imagem (.png) não funciona, mesmo se for alterado no arquivo TXT gerado.

**Comment by cpicanco** [comment]
O erro já deve ter sido corrigido, atualiaze e teste, por favor!

**Comment by AtilaCedro** [comment]
Foi corrigido sim. Só reportei o bug aqui para manter o fórum atualizado.

**Comment by cpicanco** [comment]
Obrigado!
