### ISSUE TITLE
A ferramenta de Randomização não está alterando as tentativas, apenas os nomes destas

### ISSUE THREAD

**Issue by AtilaCedro** [cpicanco/stimulus_control#46]
A ferramenta de randomização não está funcionando. As tentativas são apresentadas na ordem que foram programadas na aba "tentativas" ferramenta "MTS".

Quando abrimos o arquivo TXT para conferir, o nome da tentativa foi randomizado, mas os parâmetros não acompanham a mudança. Exemplo abaixo:

[Blc 1 - T2]
Kind=MTS
Name=**Acordes_projeto_borges_F#m->menor(a)** (nome randomizado)
Cursor=0
SStm=**Acordes_projeto_borges_C#.wav** 1 255 (acorde modelo da tentativa, que foi programado como tentativa 2 na ferramenta MTS)
SSch=CRF
NumComp=2
C1IET=0 0 1000
C1Res=HIT
C1Stm=maior(a).png 0 255
C1Sch=CRF
C2IET=0 0 1000
C2Res=MISS
C2Stm=menor(a).png 0 255
C2Sch=CRF
SBnd=300 170 300 200
**SMsg=Acordes_projeto_borges_C# - 1**
C1Bnd=300 810 300 200
C1Msg=menor(a) - 3
C2Bnd=300 490 300 200
C2Msg=maior(a) - 2

[Blc 1 - T3]
Kind=MTS
**Name=Acordes_projeto_borges_D#->maior(a)**
Cursor=0
**SStm=Acordes_projeto_borges_C#m.wav 1 255**
SSch=CRF
NumComp=2
C1IET=0 0 1000
C1Res=HIT
C1Stm=menor(a).png 0 255
C1Sch=CRF
C2IET=0 0 1000
C2Res=MISS
C2Stm=maior(a).png 0 255
C2Sch=CRF
SBnd=300 490 300 200
**SMsg=Acordes_projeto_borges_C#m - 2**
C1Bnd=300 170 300 200
C1Msg=menor(a) - 1
C2Bnd=300 810 300 200
C2Msg=maior(a) - 3

**Comment by cpicanco** [comment]
Investigarei isso.

**Comment by AtilaCedro** [comment]
Obrigado!

**Comment by cpicanco** [comment]
Comente caso a correção não funcione.
