### ISSUE TITLE
O estímulo visual da consequência aparece no tamanho original do arquivo carregado

### ISSUE THREAD

**Issue by AtilaCedro** [cpicanco/stimulus_control#47]
Quando carregada uma imagem (.png), a imagem não é afetada pela ferramenta "escrever" que permite controlar a disposição e tamanho dos estímulos visuais em cada tentativa. A imagem carregada para sinalizar consequência permanece com o tamanho original do arquivo .png carregado.

**Comment by cpicanco** [comment]
Não é possível especificar um tamanho e posição para os arquivos de consequência (especificados na chave `C1IET=`. só é possível especificar o arquivo, uma cor, forma de apresentação e tempo de apresentação, nesta ordem:

```
C1IET= exemplo.png 0 0 1000`
```

Neste momento, consequências sempre são apresentadas no centro da tela com o tamanho 500x500 (e não o tamanho original da figura).

**Comment by AtilaCedro** [comment]
Entendido, obrigado!
