### ISSUE TITLE
Sugestão - Pasta de participantes

### ISSUE THREAD

**Issue by brgsjulia** [cpicanco/stimulus_control#48]
Tenho uma sugestão para quando um novo nome de participante for colocado na aba "geral", automaticamente aparecer uma pasta nomeada com todos os arquivos necessários para iniciar o experimento.

**Comment by cpicanco** [comment]
Eu gosto da ideia, mas não estou seguro a respeito da melhor maneira de implementá-la.

**Comment by cpicanco** [comment]
Já sei como fazer isso.

- [ ] criar uma pasta padrão para os arquivos de estímulo no diretório do executável. 
- [ ] caso a pasta Media especificada pelo arquivo de configuração não seja encontrada na pasta do participante, use a pasta padrão.
- [ ] caso a pasta padrão não exista, produzir um erro.
