### ISSUE TITLE
Não consegui usa as imagens de JPG

### ISSUE THREAD

**Issue by kaimonborges** [cpicanco/stimulus_control#52]
![a1](https://user-images.githubusercontent.com/32879148/31835749-8d48a52a-b5b1-11e7-826d-5e9a3935f090.jpg)

**Comment by cpicanco** [comment]
@kaimonborges , não consegui reproduzir o problema. A figura que você envio está funcionando corretamente:
___

![screenshot - 10202017 - 03 34 54 pm](https://user-images.githubusercontent.com/6511849/31836790-dc878b74-b5ac-11e7-8da4-2f9da70b28a4.png)
___
![screenshot - 10202017 - 03 34 31 pm](https://user-images.githubusercontent.com/6511849/31836793-dd5921e8-b5ac-11e7-92d6-10c57674f048.png)
