### ISSUE TITLE
É possível editar tentativas após criar uma sessão?

### ISSUE THREAD

**Issue by louisescocio** [cpicanco/stimulus_control#56]
Depois que coloco para rodar a sessão, consigo editar as tentativas? Quando clico em configurar aparece sempre uma nova tentativa zerada para a configurar.

**Comment by cpicanco** [comment]
O que você pretende editar? A única maneira de editar tentativas é por meio do arquivo de texto. Na aba `ferramentas` você pode randomizar a posição dos estímulos de sessões já criadas. Ainda não é possível editar a ordem de tentativas de sessões já criadas, mas é possível, no momento de criação uma sessão, randomizar a ordem das tentativas e criar várias sessões.

**Comment by cpicanco** [comment]
Se você pretende usar a mesma estrutura de sessão e mudar apenas os estímulos, utilize a ferramenta de Localizar e Substituir no arquivo de texto. Por exemplo, para trocar o estímulo do modelo ( SStm=CSQ1.wav 1 200) na linha 24:

https://github.com/cpicanco/stimulus_control/blob/6e91bfbe4186c7c646f065c69dfd68a883b2ac81/docs/config_examples/linux_conditional_discrimination.txt#L17-L26

Localizar:  `SStm=CSQ1.wav`
Substituir por: `SStm=LA.avi`

Recomendo nomear os arquivos de estímulo com duas letras.

**Comment by cpicanco** [comment]
@louisescocio ?

**Comment by louisescocio** [comment]
Verifiquei que utilizei um estímulo errado e quis editar. Mas já estou seguindo o procedimento indicado. Obrigada.
