### ISSUE TITLE
ERRO NO RELATÓRIO - INCONSISTÊNCIA

### ISSUE THREAD

**Issue by kaimonborges** [cpicanco/stimulus_control#58]
No relatório produzido pelo programa após uma sessão, a coluna _Tentativa.Nome_ não está consistente com a coluna _S.Comparações_ (as duas colunas estão em cor vermelho no arquivo em anexo). Pelo que aparece no relatório a coluna _S.Comparações_ está mostrando uma tentativa a frente da que deveria mostrar, ou seja, se na coluna _Tentativa.Nome_ mostra a tentativa 1, na coluna _S.Comparações_ mostra a tentativa 2 e assim por diante. 
[ERRO NO RELATÓRIO DE SESSÃO - INCONSISTÊNCIA.xlsx](https://github.com/cpicanco/stimulus_control/files/1428170/ERRO.NO.RELATORIO.DE.SESSAO.-.INCONSISTENCIA.xlsx)

**Comment by cpicanco** [comment]
@kaimonborges , por favor, você pode anexar o arquivo de sessão (.txt) que originou o relatório?

**Comment by kaimonborges** [comment]
@cpicanco este é o arquivo.
[SESSÃO TG 1.txt](https://github.com/cpicanco/stimulus_control/files/1431952/SESSAO.TG.1.txt)

**Comment by cpicanco** [comment]
@kaimonborges você pode confirmar para mim se esta sessão foi salva após edição por meio da ferramenta "Randomizar posições"?

**Comment by kaimonborges** [comment]
@cpicanco isso mesmo, foi salvo depois da randomização.

**Comment by cpicanco** [comment]
@kaimonborges , o problema foi corrigido, por favor, baixe a versão mais recente. Lembre-se, basta substituir o arquivo `stimulus_control.exe` pelo novo.

**Comment by kaimonborges** [comment]
Muito obrigado amigão!

**Comment by kaimonborges** [comment]
desculpe @cpicanco, mas não estou conseguindo achar a nova versão, podes colocar o link aqui ?
