### ISSUE TITLE
Limite do número de comparações

### ISSUE THREAD

**Issue by kaimonborges** [cpicanco/stimulus_control#59]
Percebi que 8 comparações é o limite por tentativa. Queria saber se terá alguma atualização que possa aumentar esse número de comparações?
Necessidade: precisava utilizar 12 comparações em uma mesma tentativa.

**Comment by cpicanco** [comment]
olá @kaimonborges, não há limite de comparações por tentativa (o limite de fato existe, mas é determinado pela capacidade do computador de apresentar os estímulos, não é um limite imposto pelo programa). Você poderia me dizer aonde você encontrou esse limite?

**Comment by kaimonborges** [comment]
obrigado por responder @cpicanco. É na opção número de comparações 
![n de comparacoes](https://user-images.githubusercontent.com/32879148/32454128-70188ff4-c305-11e7-9860-7c045a74eb2d.png)
Só vai até 8 nessa opção, não consigo ir além

**Comment by cpicanco** [comment]
hummmm, hoje à noite eu irei corrigir isso @kaimonborges .

**Comment by kaimonborges** [comment]
Obrigado pela atenção

**Comment by cpicanco** [comment]
Você pode baixar a nova versão aqui: [v0.0.4.13-32-gbc211e6](https://github.com/cpicanco/stimulus_control/releases/download/v0.0.4.13/stimulus_control_win10_64bits_v0.0.4.13-32-gbc211e6.zip)
