### ISSUE TITLE
Erro no momento de colocar o estímulo 

### ISSUE THREAD

**Issue by kaimonborges** [cpicanco/stimulus_control#60]
@cpicanco aparece essa mensagem no momento de configurar as configurações.
![erro na nova versao](https://user-images.githubusercontent.com/32879148/32737796-319fadca-c882-11e7-8af8-808a85a589a5.png)
Se puder ver isso o mais rápido possível, desde já agradeço.

**Comment by cpicanco** [comment]
Olá @kaimonborges , o erro não tem relação com o estímulo, mas com o esquema de reforço. Qual configuração você colocou no esquema de reforço?

**Comment by cpicanco** [comment]
Apenas as seguintes configurações são possíveis:

- EXT
- CRF
- FR 2
- VR 5 3
- FI 5000
- VI 5000 2000
- FT 2000
- VT 3000 1000
- DRH 4 1000
- DRL 5000

Os valores podem variar.

**Comment by kaimonborges** [comment]
Seria FR 2, só que ainda não deu pra colocar, pq essa opção só aparece quando Clico em cima da Comparação. E toda vez que eu Clico em cima dela aparece essa msg, que mandei o print

**Comment by cpicanco** [comment]
Tente apertar OK e colocar FR 2.

**Comment by cpicanco** [comment]
Curioso, nunca havia ocorrido isso? Você consegue identificar o que mudou?

**Comment by kaimonborges** [comment]
Não consigo, tentei comparar com a última versão, mas não encontrei nada.

**Comment by cpicanco** [comment]
@kaimonborges, já reproduzi e identifiquei o erro. Uma nova versão estará disponível daqui algumas horas. Recomendo você usar a versão que estava funcionando para você até lá. Se tudo estiver funcionando, não atualize para a última versão. Faça isso apenas se for necessário.

**Comment by cpicanco** [comment]
@kaimonborges , uma nova versão está disponível. Por favor, baixe e teste.
