### ISSUE TITLE
Consequência

### ISSUE THREAD

**Issue by louisescocio** [cpicanco/stimulus_control#61]
É possível ampliar para tela cheia o tamanho da imagem de consequência (acerto e erro?) 

Ela aparece pequena.
![acerto sc](https://user-images.githubusercontent.com/26167396/36078057-0e4370b4-0f59-11e8-81ef-a1bcd06c2e8f.jpg)

**Comment by cpicanco** [comment]
Louise, ainda não é possível editar essa opção. Mas isso é bem simples de
resolver. Para quando você precisa?

**Comment by louisescocio** [comment]
Estou refazendo as sessões para dar início as coletas. Então o quanto antes você puder.

**Comment by cpicanco** [comment]
https://github.com/cpicanco/stimulus_control/pull/54/commits/181fe8c8ecddc25bb951a98416274df7a1ee42af

Olá @louisescocio , agora o programa usa as dimensões originais do arquivo. Não use arquivos de muito pequenos e nem maiores do que a tela.
