### ISSUE TITLE
Clique Vídeo

### ISSUE THREAD

**Issue by louisescocio** [cpicanco/stimulus_control#62]
Oi Rafael, 

Ao selecionar o esquema (CRF) o estímulo do vídeo inicia após 01 clique sobre a imagem (video). É possível configurar para que o vídeo rode novamente após outro clique em uma mesma tentativa?

**Comment by cpicanco** [comment]
Olá @louisescocio , sim é possível use um esquema de razão. Permita-me esclarecer uma coisa. Considere a seguir duas maneiras distintas de apresentar vídeos exigindo cliques:

    1. Tentativa 1. FR 2
       Quadrado Preto (Starter) -> Clique1 -> Início de um vídeo -> Final do vídeo
       Quadrado Preto (Starter) -> Clique2 -> Início de um vídeo -> Final do vídeo
       Início das Comparações
    
    2. Tentativa 2. FR 2
       Quadrado Preto (Starter) -> Clique1, Clique2 -> Início de um vídeo -> Final do vídeo
       Quadrado Preto (Starter) -> Clique1, Clique2 -> Início de um vídeo -> Final do vídeo 
       Início das Comparações
    
No primeiro caso o esquema de razão `FR 2` tem como consequência as comparações. Entretanto, no segundo caso o esquema de razão `FR 2` tem como consequência o início de um vídeo.

No `Stimulus Control` os esquemas de razão (`CRF`, `FR` e `FV`) definidos para vídeos tomam como referência o **início das comparações** e não o início dos vídeos.

**Comment by louisescocio** [comment]
Então, eu tentei colocar FR 2 mas ao clicar uma vez o vídeo roda e depois - mesmo clicando novamente - não roda mais e não aparece as alternativas.

**Comment by cpicanco** [comment]
Crie um novo Issue para esse bug.
