### ISSUE TITLE
Execução de sessões em um computador diferente do qual foi criada.

### ISSUE THREAD

**Issue by joaolsc** [cpicanco/stimulus_control#65]
Recentemente tentei criar sessões em meu computador pessoal para tentar apenas roda-las no computador da universidade que comanda os dispensadores e etc. Porém, mesmo simulando exatamente o mesmo diretório em que o SC está hospedado no computador da universidade (incluindo as mesmas mídias e etc, uma copia exata), em meu próprio computador, ao tentar executar as sessões, elas não abrem ou a tela apenas pisca e a sessão não abre. Gostaria de saber se há alguma solução para o meu problema. É possível criar sessões em um computador e executá-las em outro?

**Comment by cpicanco** [comment]
Olá João, bem vindo à comunidade do Stimulus Control.

- Certifique-se de que a mesma versão do programa está sendo usada em ambos
os computadores. Recomendo copiar a versão que funciona para o computador
de destino.

- Por favor, anexe o arquivo de configuração da sessão aqui caso você não
consiga resolver o problema.

Rafael

**Comment by cpicanco** [comment]
@joaolsc , entre em contato caso o problema ainda esteja ocorrendo.
